### PR TITLE
Fix config toml, go generate

### LINKED ISSUE #613: dumpconfig creates an invalid config.toml (ECBP1100 cannot umarshal <nil> into a *big.Int)
```
geth version
Core
Version: 1.12.14-stable
Git Commit: f1c80f7e79631ee246d56de58822619c692ebab6
Architecture: amd64
Go Version: go1.20
Operating System: linux
GOPATH=/home/ia/go
GOROOT=/home/ia/go1.21.2.linux-amd64/go

./build/bin/geth --classic dumpconfig > config.toml
INFO [02-05|09:10:00.612] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-05|09:10:00.616] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-05|09:10:00.621] Set global gas cap                       cap=50,000,000
INFO [02-05|09:10:00.631] Configured Ethereum protocol versions    capabilities="[68 67 66]"
INFO [02-05|09:10:00.631] Initializing the KZG library             backend=gokzg

./build/bin/geth --config config.toml
INFO [02-05|09:10:15.803] Starting Geth on Ethereum mainnet... 
INFO [02-05|09:10:15.803] Bumping default cache on mainnet         provided=1024 updated=4096
Fatal: config.toml, line 29: (ethconfig.Config.ECBP1100) math/big: cannot unmarshal "<nil>" into a *big.Int
```

### PR DESCRIPTION
**Pull request by meowsbits**
Fixes #613 

- [x] fix `ethconfig.Config` field data types for ECBP fields. These were `*big.Int` and should have been `*uint64`.  These data types percolate through `backend.go`.
```
	// Manual configuration field for ECBP1100 activation number. Used for modifying genesis config via CLI flag.
	ECBP1100 *uint64 `toml:",omitempty"`
	// Manual configuration field for ECBP1100's disablement block number. Used for modifying genesis config via CLI flag.
	OverrideECBP1100Deactivate *uint64 `toml:",omitempty"`
```
- [x]  `go generate` files were not up to date, so I ran `go generate -skip=trezor ./...
    - [x] and then manually edit `gen_genesis.go` to re-implement the config type switch between core-geth and go-ethereum config types (yuck!)
- [x]  install `workflow_dispatch` run trigger for the go-generate-check workflow, in addition to the existing `pull_request`

### CODE REVIEW

File: eth/ethconfig/gen_config.go [hunk 1]
```diff
@@ -131,57 +129,57 @@ func (c Config) MarshalTOML() (interface{}, error) {
...
-		DocRoot                 *string `toml:"-"`
-		EWASMInterpreter        *string
-		EVMInterpreter          *string
-		RPCGasCap               *uint64
-		RPCEVMTimeout           *time.Duration
-		RPCTxFeeCap             *float64
-		Checkpoint              *ctypes.TrustedCheckpoint      `toml:",omitempty"`
-		CheckpointOracle        *ctypes.CheckpointOracleConfig `toml:",omitempty"`
-		ECBP1100                *big.Int
-		ECBP1100Disable         *big.Int
```
Comment (diega) [inline eth/ethconfig/gen_config.go:180]: Does this change break existing toml configurations defining a `ECBP1100Disable` field? we might want to add a note about this in the release if that's the case

**Review by diega — APPROVED** [review]

File: eth/ethconfig/gen_config.go (hunk 1 above)
Comment (meowsbits) [reply eth/ethconfig/gen_config.go:180]: It _would_ theoretically break it, but it was already broken, so it only unbreaks it.
