### PR TITLE
fix Etchash cache at Mordor

### LINKED ISSUE #439: mordor fails to sync with `invalid mix digest` at block 4_980_000
#### System information

Geth version:

```
CoreGeth
Version: 1.12.4-unstable
Git Commit: 51f3e9773838367163aeb3fe8b8ef303b4415c4c
Git Commit Date: 20220103
Architecture: amd64
Go Version: go1.16
Operating System: linux
GOPATH=/root/go
GOROOT=/usr/local/go
```

```
# uname -a
Linux sf-etclabs 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

#### Expected behaviour

Syncs Mordor through blocks 5m+.

#### Actual behaviour

Loops out on encountering an invalid block.

```
Jan 07 18:56:57 sf-etclabs sh[29477]: WARN [01-07|18:56:57.917] Synchronisation failed, dropping peer    peer=f47a88a8505c5000ab6c4ef2723c0e713e79eb00e96c0741c3156bd94c608960 err="retrieved hash chain is invalid: invalid mix digest"
Jan 07 18:57:00 sf-etclabs sh[29477]: INFO [01-07|18:57:00.156] Looking for peers                        peercount=4 tried=16 static=0                                         
Jan 07 18:57:10 sf-etclabs sh[29477]: INFO [01-07|18:57:10.420] Looking for peers                        peercount=4 tried=13 static=0                                         
Jan 07 18:57:11 sf-etclabs sh[29477]: WARN [01-07|18:57:11.834] Stats server unreachable                 err="dial tcp 51.158.188.246:3000: i/o timeout"                       
Jan 07 18:57:12 sf-etclabs sh[29477]: INFO [01-07|18:57:12.095] Skip duplicated bad block                number=4,980,000 hash=cd4f82..c46a55                                  
Jan 07 18:57:12 sf-etclabs sh[29477]: ERROR[01-07|18:57:12.095]
Jan 07 18:57:12 sf-etclabs sh[29477]: ########## BAD BLOCK #########
Jan 07 18:57:12 sf-etclabs sh[29477]: Chain config: NetworkID: 7, ChainID: 63 Engine: ethash ECBP1100: 2380000 EIP1014: 301243 EIP1052: 301243 EIP1108: 999983 EIP1344: 999983 EIP140: 0 EIP145: 301243 EIP150: 0 EIP152: 999983 EIP155: 0 EIP160: 0 EIP161abc: 0 EIP161d: 0 EIP170: 0 EIP1884: 999983 EIP198: 0 EIP2028: 999983 EIP211: 0 EIP212: 0 EIP213: 0 EIP214: 0 EIP2200: 999983 EIP2565: 3985893 EIP2718: 3985893 EIP2929: 3985893 EIP2930: 3985893 EIP2: 0 EIP658: 0 EIP7: 0 EthashECIP1017: 0 EthashECIP1041: 0 EthashECIP1099: 2520000 EthashEIP100B: 0 EthashHomestead: 0
Jan 07 18:57:12 sf-etclabs sh[29477]: Number: 4980000
Jan 07 18:57:12 sf-etclabs sh[29477]: Hash: 0xcd4f821e7c0fb321626139e977df150d7af17c2f5ff7a8468e8860d9c5c46a55                                                                 
Jan 07 18:57:12 sf-etclabs sh[29477]: Error: invalid mix digest
Jan 07 18:57:12 sf-etclabs sh[29477]: ##############################
Jan 07 18:57:12 sf-etclabs sh[29477]:
Jan 07 18:57:12 sf-etclabs sh[29477]: WARN [01-07|18:57:12.101] Synchronisation failed, dropping peer    peer=b0b911904e1acc2956b66a165d802ce2a24b52a0e0331378414ff1dd5700f217 err="retrieved hash chain is invalid: invalid mix digest"
Jan 07 18:57:12 sf-etclabs sh[29477]: ERROR[01-07|18:57:12.895] Snapshot extension registration failed   peer=836158fb         err="peer connected on snap without compatible eth support"
Jan 07 18:57:20 sf-etclabs sh[29477]: INFO [01-07|18:57:20.475] Looking for peers                        peercount=3 tried=16 static=0
Jan 07 18:57:24 sf-etclabs sh[29477]: INFO [01-07|18:57:24.449] Skip duplicated bad block                number=4,980,000 hash=cd4f82..c46a55
Jan 07 18:57:24 sf-etclabs sh[29477]: ERROR[01-07|18:57:24.450]
Jan 07 18:57:24 sf-etclabs sh[29477]: ########## BAD BLOCK #########
Jan 07 18:57:24 sf-etclabs sh[29477]: Chain config: NetworkID: 7, ChainID: 63 Engine: ethash ECBP1100: 2380000 EIP1014: 301243 EIP1052: 301243 EIP1108: 999983 EIP1344: 999983 EIP140: 0 EIP145: 301243 EIP150: 0 EIP152: 999983 EIP155: 0 EIP160: 0 EIP161abc: 0 EIP161d: 0 EIP170: 0 EIP1884: 999983 EIP198: 0 EIP2028: 999983 EIP211: 0 EIP212: 0 EIP213: 0 EIP214: 0 EIP2200: 999983 EIP2565: 3985893 EIP2718: 3985893 EIP2929: 3985893 EIP2930: 3985893 EIP2: 0 EIP658: 0 EIP7: 0 EthashECIP1017: 0 EthashECIP1041: 0 EthashECIP1099: 2520000 EthashEIP100B: 0 EthashHomestead: 0
Jan 07 18:57:24 sf-etclabs sh[29477]: Number: 4980000
Jan 07 18:57:24 sf-etclabs sh[29477]: Hash: 0xcd4f821e7c0fb321626139e977df150d7af17c2f5ff7a8468e8860d9c5c46a55
Jan 07 18:57:24 sf-etclabs sh[29477]: Error: invalid mix digest
Jan 07 18:57:24 sf-etclabs sh[29477]: ##############################
Jan 07 18:57:24 sf-etclabs sh[29477]:  
Jan 07 18:57:24 sf-etclabs sh[29477]: WARN [01-07|18:57:24.450] Synchronisation failed, dropping peer    peer=35aabeacb0448d4505f09c93f89206441d7831fdb28afb9b10e0b5326f22a1d2 err="retrieved hash chain is invalid: invalid mix digest"
Jan 07 18:57:24 sf-etclabs systemd[1]: Stopping CoreGeth Ethereum Classic - Mordor...
```

#### Steps to reproduce the behaviour

Below is the system file.
I have attempted `systemctl restart`s multiple times. I have purged the entire datadir (which in my configuration contains the ethash dirs) mutliple times, resyncing from scratch. The issue persists.

```
# cat /etc/systemd/system/coregeth_ethereumclassic_mordor.service
[Unit]
Description=CoreGeth Ethereum Classic - Mordor

[Service]
Type=simple
User=root
Restart=always
RestartSec=3
TimeoutStopSec=10min
MemoryHigh=3600000000
#MemoryMax=2000000000
Environment="GETH=/home/u/go/src/github.com/ethereum/go-ethereum/build/bin/geth"
ExecStart=/bin/sh -c '${GETH} --mordor \
        --syncmode=fast \
        --datadir /mnt/volume_sfo2_01/mordor \
        --cache 512 \
        --verbosity 5 \
        --ipcpath /home/u/go/src/github.com/ethereum/go-ethereum/coregeth_ethereumclassic_mordor.ipc \
        --mine \
        --miner.etherbase=0x877bd459c9b7d8576b44e59e09d076c25946f443 \
        --light.serve 80 \
        --ethash.dagsinmem=0 \
        --ethash.dagdir /mnt/volume_sfo2_01/mordor/ethash \
        --miner.gastarget 64000000 \
        --miner.gaslimit 128000000 \
        --ethstats "ETC Labs Metrics meowsbits":Goo0y@ws://mordor.dash.fault.dev:3003 \
        --metrics \
        --metrics.expensive \
        --metrics.addr=0.0.0.0 \
        --metrics.influxdb \
        --metrics.influxdb.endpoint=https://influx.metrics.etccore.in \
        --metrics.influxdb.database=xxx \
        --metrics.influxdb.username=xxx \
        --metrics.influxdb.password=xxx \
        --metrics.influxdb.tags=chain=mordor,owner=isaac,host=isaac-sfetclabs,gethv=$(${GETH} version | grep -E '^Version' | cut -d" " -f2) \
        --pprof --pprof.addr=0.0.0.0 --pprof.port=6069 \
        --http --http.port 8111'
ExecStartPost=/bin/sh -c 'sleep 15; chmod 777 /home/u/go/src/github.com/ethereum/go-ethereum/coregeth_ethereumclassic_mordor.ipc'

[Install]
WantedBy=default.target
```

#### Backtrace

````
[backtrace]
````

### PR DESCRIPTION
**Pull request by meowsbits**
Fixes #439 and #493. 

Please read commit messages for more context, but here's an overview:
- the bug was because of a bad `future item` in the in-memory lru cache
  + the post-ECIP1099 epochs caught up to pre-ECIP1099 epoch numbers and caused a bad cache hit
- cache files were named with `seed hashes`, which are hard to identify when epochs are not continuous
  + so I introduce a new filename scheme which includes epoch values and allows a scanner to identify and remove them as needed (avoiding a potential other bad-cache-hit scenario when seed hashes collide between pre- and post-ECIP1099 epochs)

This PR (and branch) uses #496 as a base. 

Here's Mordor passing 4_980_000 without issue:

```
INFO [08-30|09:17:28.928|core/headerchain.go:407]              Imported new block headers               count=256  elapsed=6.923ms     number=4,963,200 hash=581a33..ec7fda age=10mo1w3d                 
INFO [08-30|09:17:29.053|core/headerchain.go:407]              Imported new block headers               count=576  elapsed=124.596ms   number=4,963,776 hash=3aebf0..8eae21 age=10mo1w3d                 
INFO [08-30|09:17:29.246|core/blockchain.go:1214]              Imported new block receipts              count=190  elapsed=294.043ms   number=4,954,942 hash=489fd5..847757 age=10mo1w5d   size=63.34KiB 
INFO [08-30|09:17:29.534|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=281.566ms   number=4,956,990 hash=5d3baa..490a1f age=10mo1w4d   size=681.45KiB
INFO [08-30|09:17:29.826|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=286.437ms   number=4,959,038 hash=ff6d35..acb684 age=10mo1w4d   size=679.64KiB           
INFO [08-30|09:17:30.092|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=260.763ms   number=4,961,086 hash=9580f2..c100ae age=10mo1w4d   size=680.47KiB
INFO [08-30|09:17:30.364|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=265.470ms   number=4,963,134 hash=5bc83c..76c6e2 age=10mo1w3d   size=680.05KiB
INFO [08-30|09:17:30.614|core/blockchain.go:1214]              Imported new block receipts              count=642  elapsed=248.286ms   number=4,963,776 hash=3aebf0..8eae21 age=10mo1w3d   size=213.64KiB
INFO [08-30|09:17:30.872|core/headerchain.go:407]              Imported new block headers               count=576  elapsed=10.723ms    number=4,964,352 hash=e9a550..3151f5 age=10mo1w3d                 
INFO [08-30|09:17:31.144|core/blockchain.go:1214]              Imported new block receipts              count=61   elapsed=269.739ms   number=4,963,837 hash=96fa97..dbc97d age=10mo1w3d   size=20.24KiB
INFO [08-30|09:17:31.409|core/blockchain.go:1214]              Imported new block receipts              count=515  elapsed=263.677ms   number=4,964,352 hash=e9a550..3151f5 age=10mo1w3d   size=170.94KiB
INFO [08-30|09:17:31.495|core/headerchain.go:407]              Imported new block headers               count=192  elapsed=5.957ms     number=4,964,544 hash=1f3ff3..982112 age=10mo1w3d                 
INFO [08-30|09:17:31.756|core/blockchain.go:1214]              Imported new block receipts              count=192  elapsed=260.431ms   number=4,964,544 hash=1f3ff3..982112 age=10mo1w3d   size=63.62KiB 
INFO [08-30|09:17:34.519|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=79.619ms    number=4,966,592 hash=0d0324..14930c age=10mo1w3d                 
INFO [08-30|09:17:34.595|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=75.533ms    number=4,968,640 hash=cd1be2..1c9e07 age=10mo1w3d                 
INFO [08-30|09:17:34.670|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=73.257ms    number=4,970,688 hash=448753..9a8e81 age=10mo1w2d                 
INFO [08-30|09:17:34.756|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=86.058ms    number=4,972,736 hash=55a87e..45b1f4 age=10mo1w2d 
INFO [08-30|09:17:34.837|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=79.494ms    number=4,974,784 hash=9ffeef..a981dc age=10mo1w2d                 
INFO [08-30|09:17:34.900|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=62.553ms    number=4,976,832 hash=d38358..70604e age=10mo1w1d                 
INFO [08-30|09:17:34.955|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=54.026ms    number=4,978,880 hash=f4bac1..2c628f age=10mo1w1d                 
INFO [08-30|09:17:35.000|core/headerchain.go:407]              Imported new block headers               count=448  elapsed=44.670ms    number=4,979,328 hash=181f9d..e06a3c age=10mo1w1d                 
TRACE[08-30|09:17:35.009|consensus/ethash/ethash.go:217]       Evicted ethash cache                     epoch=81-60000                                                                                   
TRACE[08-30|09:17:35.009|consensus/ethash/ethash.go:257]       Requiring new future ethash cache        epoch=84                                                                         
DEBUG[08-30|09:17:35.010|consensus/ethash/ethash.go:368]       Failed to load old ethash cache          epoch=84       epochLength=60000 err="open /home/ia/.myethash-cache/cache-R23-84-a8784097a4d03c2d: no such file or directory"
INFO [08-30|09:17:35.042|core/headerchain.go:407]              Imported new block headers               count=768  elapsed=40.908ms    number=4,980,096 hash=07fb15..40f606 age=10mo1w1d                 
INFO [08-30|09:17:35.318|core/blockchain.go:1214]              Imported new block receipts              count=133  elapsed=264.958ms   number=4,964,677 hash=b17bcb..4807de age=10mo1w3d   size=44.12KiB 
INFO [08-30|09:17:35.593|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=269.068ms   number=4,966,725 hash=a3fdb5..6c8663 age=10mo1w3d   size=681.19KiB
INFO [08-30|09:17:35.877|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=276.736ms   number=4,968,773 hash=877640..3f5902 age=10mo1w3d   size=680.50KiB
DEBUG[08-30|09:17:35.929|consensus/ethash/algorithm.go:176]    Generated ethash verification cache      epoch=84       epochLength=60000 elapsed=915.834ms                                               
DEBUG[08-30|09:17:35.931|consensus/ethash/ethash.go:402]       Deleted ethash cache file                epoch=84       epochLength=60000 target.epoch=81 file=/home/ia/.myethash-cache/cache-R23-81-a92afa474bb50595
INFO [08-30|09:17:36.217|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=332.756ms   number=4,970,821 hash=62f824..981d8d age=10mo1w2d   size=683.95KiB
INFO [08-30|09:17:36.551|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=327.462ms   number=4,972,869 hash=98b78b..9cb63a age=10mo1w2d   size=680.60KiB
INFO [08-30|09:17:36.843|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=285.500ms   number=4,974,917 hash=b8060c..aae609 age=10mo1w2d   size=681.48KiB
INFO [08-30|09:17:37.198|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=347.532ms   number=4,976,965 hash=9bf489..ccf302 age=10mo1w1d   size=682.86KiB
INFO [08-30|09:17:37.502|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=190.267ms   number=4,982,144 hash=4a3de1..24b18d age=10mo1w1d
INFO [08-30|09:17:37.547|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=339.889ms   number=4,979,013 hash=61dbe4..b02121 age=10mo1w1d   size=680.57KiB
INFO [08-30|09:17:37.705|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=202.039ms   number=4,984,192 hash=66175c..b94432 age=10mo1w18h
INFO [08-30|09:17:37.907|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=201.292ms   number=4,986,240 hash=0132ca..c574f0 age=10mo1w11h
INFO [08-30|09:17:37.915|core/blockchain.go:1214]              Imported new block receipts              count=1083 elapsed=364.230ms   number=4,980,096 hash=07fb15..40f606 age=10mo1w1d   size=359.65KiB
INFO [08-30|09:17:38.225|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=317.752ms   number=4,988,288 hash=c34faa..ccab35 age=10mo1w4h
INFO [08-30|09:17:38.246|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=322.386ms   number=4,982,144 hash=4a3de1..24b18d age=10mo1w1d   size=676.31KiB
INFO [08-30|09:17:38.312|core/headerchain.go:407]              Imported new block headers               count=640  elapsed=86.325ms    number=4,988,928 hash=391503..500c35 age=10mo1w2h
INFO [08-30|09:17:38.521|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=265.879ms   number=4,984,192 hash=66175c..b94432 age=10mo1w18h  size=675.95KiB
INFO [08-30|09:17:38.896|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=366.782ms   number=4,986,240 hash=0132ca..c574f0 age=10mo1w11h  size=675.63KiB
INFO [08-30|09:17:39.201|core/blockchain.go:1214]              Imported new block receipts              count=2048 elapsed=298.374ms   number=4,988,288 hash=c34faa..ccab35 age=10mo1w4h   size=679.56KiB
INFO [08-30|09:17:39.504|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=133.771ms   number=4,990,976 hash=b371fd..c30a7d age=10mo6d18h
INFO [08-30|09:17:39.517|core/blockchain.go:1214]              Imported new block receipts              count=640  elapsed=313.894ms   number=4,988,928 hash=391503..500c35 age=10mo1w2h   size=211.31KiB
INFO [08-30|09:17:39.572|core/headerchain.go:407]              Imported new block headers               count=2048 elapsed=67.025ms    number=4,993,024 hash=61c843..9c49c7 age=10mo6d11h
```

Here's `--vmodule=consensus/*=6` logs during the same time context:
```
> tail -F geth.out |grep --line-buffered -E 'consensus' 
[...]
TRACE[08-30|09:16:52.950|consensus/ethash/ethash.go:257]       Requiring new future ethash cache        epoch=81                                                                                                                                                                                                                                 [0/15]
DEBUG[08-30|09:16:52.950|consensus/ethash/ethash.go:368]       Failed to load old ethash cache          epoch=81       epochLength=60000 err="open /home/ia/.myethash-cache/cache-R23-81-a92afa474bb50595: no such file or directory"
DEBUG[08-30|09:16:53.870|consensus/ethash/algorithm.go:176]    Generated ethash verification cache      epoch=81       epochLength=60000 elapsed=918.574ms
DEBUG[08-30|09:16:53.872|consensus/ethash/ethash.go:402]       Deleted ethash cache file                epoch=81       epochLength=60000 target.epoch=78 file=/home/ia/.myethash-cache/cache-R23-78-7b1e42ac7d205c8d
TRACE[08-30|09:17:04.349|consensus/ethash/ethash.go:217]       Evicted ethash cache                     epoch=79-60000
TRACE[08-30|09:17:04.350|consensus/ethash/ethash.go:257]       Requiring new future ethash cache        epoch=82
DEBUG[08-30|09:17:04.351|consensus/ethash/ethash.go:368]       Failed to load old ethash cache          epoch=82       epochLength=60000 err="open /home/ia/.myethash-cache/cache-R23-82-d5d85ca518675140: no such file or directory"
DEBUG[08-30|09:17:05.271|consensus/ethash/algorithm.go:176]    Generated ethash verification cache      epoch=82       epochLength=60000 elapsed=918.033ms
DEBUG[08-30|09:17:05.272|consensus/ethash/ethash.go:402]       Deleted ethash cache file                epoch=82       epochLength=60000 target.epoch=79 file=/home/ia/.myethash-cache/cache-R23-79-9d2e3fc27256471a
TRACE[08-30|09:17:17.520|consensus/ethash/ethash.go:217]       Evicted ethash cache                     epoch=80-60000
TRACE[08-30|09:17:17.520|consensus/ethash/ethash.go:257]       Requiring new future ethash cache        epoch=83
DEBUG[08-30|09:17:17.525|consensus/ethash/ethash.go:368]       Failed to load old ethash cache          epoch=83       epochLength=60000 err="open /home/ia/.myethash-cache/cache-R23-83-3aa8f28cac16bdd8: no such file or directory"
DEBUG[08-30|09:17:18.443|consensus/ethash/algorithm.go:176]    Generated ethash verification cache      epoch=83       epochLength=60000 elapsed=916.915ms
DEBUG[08-30|09:17:18.444|consensus/ethash/ethash.go:402]       Deleted ethash cache file                epoch=83       epochLength=60000 target.epoch=80 file=/home/ia/.myethash-cache/cache-R23-80-10fc9a2e5b65ea3f
TRACE[08-30|09:17:35.009|consensus/ethash/ethash.go:217]       Evicted ethash cache                     epoch=81-60000
TRACE[08-30|09:17:35.009|consensus/ethash/ethash.go:257]       Requiring new future ethash cache        epoch=84
DEBUG[08-30|09:17:35.010|consensus/ethash/ethash.go:368]       Failed to load old ethash cache          epoch=84       epochLength=60000 err="open /home/ia/.myethash-cache/cache-R23-84-a8784097a4d03c2d: no such file or directory"
DEBUG[08-30|09:17:35.929|consensus/ethash/algorithm.go:176]    Generated ethash verification cache      epoch=84       epochLength=60000 elapsed=915.834ms
DEBUG[08-30|09:17:35.931|consensus/ethash/ethash.go:402]       Deleted ethash cache file                epoch=84       epochLength=60000 target.epoch=81 file=/home/ia/.myethash-cache/cache-R23-81-a92afa474bb50595
TRACE[08-30|09:17:51.206|consensus/ethash/ethash.go:217]       Evicted ethash cache                     epoch=82-60000
TRACE[08-30|09:17:51.206|consensus/ethash/ethash.go:257]       Requiring new future ethash cache        epoch=85
DEBUG[08-30|09:17:51.206|consensus/ethash/ethash.go:368]       Failed to load old ethash cache          epoch=85       epochLength=60000 err="open /home/ia/.myethash-cache/cache-R23-85-4e99a30e99712c8c: no such file or directory"
DEBUG[08-30|09:17:52.130|consensus/ethash/algorithm.go:176]    Generated ethash verification cache      epoch=85       epochLength=60000 elapsed=922.632ms
DEBUG[08-30|09:17:52.131|consensus/ethash/ethash.go:402]       Deleted ethash cache file                epoch=85       epochLength=60000 target.epoch=82 file=/home/ia/.myethash-cache/cache-R23-82-d5d85ca518675140
```

### CODE REVIEW

File: consensus/ethash/ethash.go [hunk 1]
```diff
@@ -250,7 +250,9 @@ func (lru *lru) get(epoch uint64, epochLength uint64, ecip1099FBlock *uint64) (i
 	}
 
 	// Update the 'future item' if epoch is larger than previously seen.
-	if epoch < maxEpoch-1 && lru.future < nextEpoch {
+	// Last conditional clause ('lru.future > nextEpoch') handles the ECIP1099 case where
+	// the next epoch is expected to be LESSER THAN that of the previous state's future epoch number.
+	if epoch < maxEpoch-1 && (lru.future < nextEpoch || lru.future > nextEpoch) {
```
Comment (ziogaschr) [inline consensus/ethash/ethash.go]: I wonder if this, will be easier to read `if epoch < maxEpoch-1 && lru.future != nextEpoch {` or harder to understand the intention of the code.

Comment (meowsbits) [reply consensus/ethash/ethash.go]: Ah, nice catch! I think your way is readable and understandable too. Will patch.

File: consensus/ethash/ethash.go [hunk 2]
```diff
@@ -226,31 +226,34 @@ func (lru *lru) get(epoch uint64, epochLength uint64, ecip1099FBlock *uint64) (i
...
+		lru.cache.Add(cacheKey, item)
 	}
 
 	// Ensure pre-generation handles ecip-1099 changeover correctly
 	var nextEpoch = epoch + 1
 	var nextEpochLength = epochLength
 	if ecip1099FBlock != nil {
 		nextEpochBlock := nextEpoch * epochLength
-		if nextEpochBlock == *ecip1099FBlock && epochLength == epochLengthDefault {
+		if nextEpochBlock >= *ecip1099FBlock && epochLength == epochLengthDefault {
```
Comment (meowsbits) [inline consensus/ethash/ethash.go]: Introduced at commit f4c42dcc40b7b2778957944141d2edd1d972f038.
I think maybe I'd better revert this; it may be too generous.

Suppose ECIP1099 is activated at block 3_000_042.
Then the `nextEpoch` will begin at 3_030_000, lasting till 3_090_000. 

From the [spec](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1099.md#implementation):
> For the smoothest possible transition activation should occur on a block in which an epoch transition to an even epoch number is occurring.

Agree?

Comment (ziogaschr) [reply consensus/ethash/ethash.go]: Yes, I would stick to the spec. Haven't checked the spec while reviewing.

**Comment by ziogaschr** [comment]
Fresh syncing with Mordor finished just fine. Once you make the small changes in comments, I will approve this PR.
Nice work man, once more.

File: consensus/ethash/ethash.go (hunk 1 above)
Comment (meowsbits) [reply consensus/ethash/ethash.go]: Resolved with https://github.com/etclabscore/core-geth/pull/499/commits/bac80dae1ea98d4acae701077c9f09d78dd406d0

File: consensus/ethash/ethash.go (hunk 2 above)
Comment (meowsbits) [reply consensus/ethash/ethash.go]: Resolved with https://github.com/etclabscore/core-geth/pull/499/commits/545a964e57fa490dcd8aa973e5a2ecc268625fa7

**Comment by meowsbits** [comment]
Review comments are addressed and resolved (links to associated commits in review comments).
I added a few more tests in latest commits as well.

**Comment by meowsbits** [comment]
@ziogaschr PTAL https://github.com/etclabscore/core-geth/pull/499/commits/69f5300a9d53376b488b2e59c25b37df9c7af628

This proposes keeping the file naming scheme identical between the cache and full dataset. 
The logic for both automatically removes "legacy" files, meaning that this upgrade will cause all DAG files to be regenerated, using the new naming pattern. 

- Does the new naming pattern LGTY?
- Should this be considered an API-breaking change?
- Should we add logic to _move_ existing files to the new name scheme? (Instead of plainly recreating new and rming old.)

File: consensus/ethash/ethash.go [hunk 3]
```diff
@@ -429,7 +463,7 @@ func (d *dataset) generate(dir string, limit int, lock bool, test bool) {
 		if !isLittleEndian() {
 			endian = ".be"
 		}
-		path := filepath.Join(dir, fmt.Sprintf("full-R%d-%x%s", algorithmRevision, seed[:8], endian))
+		path := filepath.Join(dir, fmt.Sprintf("full-R%d-%d-%x%s", algorithmRevision, seed[:8], d.epoch, endian))
```
Comment (ziogaschr) [inline consensus/ethash/ethash.go]: The `seed` and `epoch` args are in the opposite order from [cache](https://github.com/etclabscore/core-geth/pull/499/files#diff-81dd4f9d1a46a485d74affabbf00bcc61fd98a44bcf785a57d59d87ce50ddb93R351). Is this intentional?

Comment (meowsbits) [reply consensus/ethash/ethash.go]: :man_facepalming: :1st_place_medal:

Comment (meowsbits) [reply consensus/ethash/ethash.go]: See https://github.com/etclabscore/core-geth/pull/499/commits/310ca59020c0f7887ef0952ddbefc117e8eab6da.

**Comment by ziogaschr** [comment]
During the ECIP-1099 transition we handled the renaming of existing DAGs, from what I recall it has been done for smoother transition times, so as not all miners had to wait for DAG generation for the next block.
At this time, I consider it's not needed to handle this case, as probably each miner will upgrade the node at different time.

API-breaking change: I don't think it is, my only worry is, if any GPU mining software, is using/sharing the same DAG files. I don't think so.

Once the above checked, I vote on just removing all old files and recreating from scratch.

**Comment by meowsbits** [comment]
Yea, the GPU miners I've used seem to generate their own DAGs (which makes sense because a user could configure `--ethash.dagdir` to be somewhere unexpected and I've never seen a GPU miner with a flag for it).

I too am OK with regenerating and rming the old DAGs. Let's do it. KISS.

**Review by ziogaschr — APPROVED** [review]

**Comment by blackmennewstyle** [comment]
> During the ECIP-1099 transition we handled the renaming of existing DAGs, from what I recall it has been done for smoother transition times, so as not all miners had to wait for DAG generation for the next block. At this time, I consider it's not needed to handle this case, as probably each miner will upgrade the node at different time.
> 
> API-breaking change: I don't think it is, my only worry is, if any GPU mining software, is using/sharing the same DAG files. I don't think so.
> 
> Once the above checked, I vote on just removing all old files and recreating from scratch.

Well that decision actually kinda breaks the implementation of `ETC` inside  `miningcore` (stratum mining pool software) since it allows to share that `.etchash` folder and the C++ ethash library uses the old naming format. It was handy to be able to use the DAG files directly generated by `core-geth` but now unfortunately that feature will no longer work unless we go back to core-geth `1.12.8` lol

**Comment by ziogaschr** [comment]
@blackmennewstyle good to know that you use DAG files this way, we couldn't find any use-cases like this one.
I wonder if it's easy for you to handle the new pattern in your code?

We will also discuss with @meowsbits, what would mean for us to provide the old naming.
Will keep you posted.

**Comment by ziogaschr** [comment]
@blackmennewstyle can you please create a new issue and add a link to this one?

**Comment by blackmennewstyle** [comment]
@ziogaschr The naming we use is exactly the one which has been deleted in this commit: https://github.com/etclabscore/core-geth/pull/499/files#diff-81dd4f9d1a46a485d74affabbf00bcc61fd98a44bcf785a57d59d87ce50ddb93L432

**Comment by ziogaschr** [comment]
@blackmennewstyle yes I understood this. Was just checking with you if you could have a different pattern (our new one) in your code under certain circumstances.

**Comment by blackmennewstyle** [comment]
@ziogaschr I believe we can since the C++ `etchash` library which is used inside `miningcore` was based on this one: https://github.com/etclabscore/cpp-etchash

We probably need to find out the functions which are used to handle and generate the DAG file and adjust the naming scheme to the new one. While still allowing the `deleted` naming scheme since previous core-geth releases are based on it lol

**Comment by meowsbits** [comment]
Hey @blackmennewstyle. Thanks for your report, I'm getting caught up here.

> breaks the implementation of ETC inside miningcore (stratum mining pool software) since it allows to share that .etchash folder and the C++ ethash library uses the old naming format. 

I don't see any reference to geth's DAG cache files in there yet. And the actual source used by `miningcore` is closed, or? 
- https://github.com/search?q=repo%3Aetclabscore%2Fcpp-etchash+etchash&type=code
- https://github.com/search?q=repo%3Aetclabscore%2Fcpp-etchash+ethash&type=code

> actually kinda breaks the implementation of ETC inside `miningcore`

Can you provide logs or some more further detail on what "kinda breaks" looks like?
Are we expecting (or hoping) to resolve this by basically adding a `\-%d` to some regex at `miningcore` or `cpp-etchash`? 

PS. Bummer that the change broke the dep, but IMO a cache file footprint should not be considered a stable API surface for mining pools...

**Comment by blackmennewstyle** [comment]
> Hey @blackmennewstyle. Thanks for your report, I'm getting caught up here.
> 
> > breaks the implementation of ETC inside miningcore (stratum mining pool software) since it allows to share that .etchash folder and the C++ ethash library uses the old naming format.
> 
> I don't see any reference to geth's DAG cache files in there yet. And the actual source used by `miningcore` is closed, or?
> 
>     * https://github.com/search?q=repo%3Aetclabscore%2Fcpp-etchash+etchash&type=code
> 
>     * https://github.com/search?q=repo%3Aetclabscore%2Fcpp-etchash+ethash&type=code
> 
> 
> > actually kinda breaks the implementation of ETC inside `miningcore`
> 
> Can you provide logs or some more further detail on what "kinda breaks" looks like? Are we expecting (or hoping) to resolve this by basically adding a `\-%d` to some regex at `miningcore` or `cpp-etchash`?
> 
> PS. Bummer that the change broke the dep, but IMO a cache file footprint should not be considered a stable API surface for mining pools...

`miningcore` is totally open-source. The reason, you don't see the code on the main branch is because now it's only available on the `dev` branch - https://github.com/oliverw/miningcore/tree/dev/src/Native/libetchash - Also, there is currently a discussion and evolution about using the full DAG or light DAG - https://github.com/oliverw/miningcore/pull/1608 - Long story short some people hate using the FULL DAG because the generation takes too long, one trickery was to take advantage of `core-geth` since it was generating them just like the C++ `etchash` library expects them. But not everyone can enjoy that scenario since server configurations come in many flavors, some people don't run their stratum mining pool  and `core-geth` on the same machine. So they were using the light DAG implementation. But reports suggest light DAG increases pool latency in some scenarios.

The break is not critical since `miningcore` will generate the DAG file with the legacy naming if it does not find them, however your code seems to delete these legacy files if they are present inside the `.etchash` folder - https://github.com/etclabscore/core-geth/pull/499/files#diff-81dd4f9d1a46a485d74affabbf00bcc61fd98a44bcf785a57d59d87ce50ddb93R512

**Comment by meowsbits** [comment]
So maybe `miningcore` can just use its own data dir? To my knowledge, neither core-geth nor go-ethereum expose that path or its data as a stable API.

**Comment by blackmennewstyle** [comment]
> So maybe `miningcore` can just use its own data dir? To my knowledge, neither core-geth nor go-ethereum expose that path or its data as a stable API.

No worry,`miningcore` offers the possibility to set manually the path where the DAG file should be generated.

I actually found the mechanism in our `etchash` implementation - Default directory: https://github.com/oliverw/miningcore/blob/dev/src/Native/libetchash/io_posix.c#L91 an the legacy naming: https://github.com/oliverw/miningcore/blob/dev/src/Native/libetchash/io.h#L207

It does not seem to be an easy modification to support your new naming, it will require lot of code changes through multiple functions.
