### PR TITLE
miner: exit loop when downloader Done or Failed

### LINKED ISSUE #199: Mining aborted due to sync
#### System information

Geth version: `1,11,15`
OS & Version: ubuntu

Mining aborted due to sync (150 peers)

### PR DESCRIPTION
**Pull request by meowsbits**
Following the logic of the comment at the method,
this fixes a regression introduced at 7cf56d6f064869cb62b1673f9ee437020c595391
, which would allow external parties to DoS with
blocks, preventing mining progress.

Rel #199 

Corresponding upstream PR at https://github.com/ethereum/go-ethereum/pull/21653

### CODE REVIEW

**Comment by iquidus** [comment]
after implementing these changes force interupt, (e.g ctrl+c) is not exiting cleanly, as it did prior to these changes. I am forced to interupt until panic, otherwise looping on looking for peers.

```
INFO [10-05|14:42:51.369] Ethereum protocol stopped 
INFO [10-05|14:42:51.369] Transaction pool stopped 
INFO [10-05|14:42:59.009] Looking for peers                        peercount=0 tried=17 static=0
INFO [10-05|14:43:09.039] Looking for peers                        peercount=0 tried=51 static=0
INFO [10-05|14:43:19.544] Looking for peers                        peercount=0 tried=65 static=0
INFO [10-05|14:43:29.627] Looking for peers                        peercount=0 tried=69 static=0
INFO [10-05|14:43:39.882] Looking for peers                        peercount=0 tried=38 static=0
INFO [10-05|14:43:50.282] Looking for peers                        peercount=1 tried=98 static=0
INFO [10-05|14:44:00.283] Looking for peers                        peercount=0 tried=98 static=0
INFO [10-05|14:44:10.343] Looking for peers                        peercount=1 tried=59 static=0
INFO [10-05|14:44:20.387] Looking for peers                        peercount=1 tried=75 static=0
INFO [10-05|14:44:30.544] Looking for peers                        peercount=1 tried=92 static=0
INFO [10-05|14:44:40.570] Looking for peers                        peercount=1 tried=62 static=0
INFO [10-05|14:44:50.700] Looking for peers                        peercount=0 tried=60 static=0
```

**Comment by meowsbits** [comment]
@iquidus Yes, it needs more work. The channels are not getting closed. See upstream PR for comments as well.

**Comment by meowsbits** [comment]
@iquidus @ziogaschr PTAL

File: miner/miner.go [hunk 1]
```diff
@@ -80,47 +80,66 @@ func New(eth Backend, config *Config, chainConfig ctypes.ChainConfigurator, mux
...
+			downloaderEvents.Unsubscribe()
+		}
+	}
+
 	for {
 		select {
-		case ev := <-events.Chan():
+		case ev := <-downloaderEvents.Chan():
 			if ev == nil {
 				return
```
Comment (ziogaschr) [inline miner/miner.go]: @meowsbits I think that if it returns at this point it will break the code, as also the `startCh` and `stopCh` will not be handled too. Maybe we can change this with a `continue`.

Comment (meowsbits) [reply miner/miner.go]: Nice catch, thanks! I've added a test for this case and fixed handling the subscription events by using a dedicated go routine to avoid a busy loop. https://github.com/etclabscore/core-geth/pull/200/commits/990fc669c81b958e579e1500835fc14fe79832b9

**Review by iquidus — APPROVED** [review]
lgtm

**Review by ziogaschr — APPROVED** [review]
