### PR TITLE
light: fix txpool causes panic on reorgOnNewHead

### LINKED ISSUE #53: panic at les txpool reorg
#### System information

Geth version: v1.11.0-core
OS & Version: Linux

#### Actual behaviour
```
Mar 04 12:22:51 sf-etclabs sh[26575]: WARN [03-04|12:22:51.621] Skipping faucet refresh, head too old    number=778682 hash=5a1633…3c13bf age=1mo3d16h   
Mar 04 12:22:51 sf-etclabs sh[26575]: WARN [03-04|12:22:51.622] Skipping faucet refresh, head too old    number=778683 hash=145cc7…01f163 age=1mo3d16h   
Mar 04 12:22:51 sf-etclabs sh[26575]: WARN [03-04|12:22:51.622] Skipping faucet refresh, head too old    number=778684 hash=74d573…562392 age=1mo3d16h   
Mar 04 12:22:51 sf-etclabs sh[26575]: panic: runtime error: invalid memory address or nil pointer dereference                                            
Mar 04 12:22:51 sf-etclabs sh[26575]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc5937c]                                           
Mar 04 12:22:51 sf-etclabs sh[26575]: goroutine 57 [running]:                                                                                            
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).reorgOnNewHead(0xc00038cc60, 0x11a2960, 0xc0204bd920, 0xc0209ec480,
0xc0204bd920, 0xc02096eb00, 0x8)                                                                                                                         
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:230 +0x23c                                    
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).setNewHead(0xc00038cc60, 0xc0209ec480)                             
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:311 +0x13a                                    
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).eventLoop(0xc00038cc60)                                            
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:292 +0x53                                     
Mar 04 12:22:51 sf-etclabs sh[26575]: created by github.com/ethereum/go-ethereum/light.NewTxPool                                                         
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:109 +0x3eb                                    
```

#### Steps to reproduce the behaviour

Run `faucet`, need reorg.

### PR DESCRIPTION
**Pull request by meowsbits**
Fixes #53 

```
panic: runtime error: invalid memory address or nil pointer dereference
Mar 04 12:22:51 sf-etclabs sh[26575]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xc5937c]
Mar 04 12:22:51 sf-etclabs sh[26575]: goroutine 57 [running]:
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).reorgOnNewHead(0xc00038cc60, 0x11a2960, 0xc0204bd920, 0xc0209ec480,
0xc0204bd920, 0xc02096eb00, 0x8)
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:230 +0x23c
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).setNewHead(0xc00038cc60, 0xc0209ec480)
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:311 +0x13a
Mar 04 12:22:51 sf-etclabs sh[26575]: github.com/ethereum/go-ethereum/light.(*TxPool).eventLoop(0xc00038cc60)
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:292 +0x53
Mar 04 12:22:51 sf-etclabs sh[26575]: created by github.com/ethereum/go-ethereum/light.NewTxPool
Mar 04 12:22:51 sf-etclabs sh[26575]:         /root/go/src/github.com/ethereum/go-ethereum/light/txpool.go:109 +0x3eb
```

Signed-off-by: meows <b5c6@protonmail.com>

### CODE REVIEW

**Comment by meowsbits** [comment]
@tzdybal If and when LGTY, we can merge it and then I'll also make the corresponding PR at ethereum/go-ethereum.

**Comment by meowsbits** [comment]
beep @tzdybal

File: light/txpool.go [hunk 1]
```diff
@@ -224,30 +224,38 @@ func (pool *TxPool) reorgOnNewHead(ctx context.Context, newHeader *types.Header)
...
+		pool.head = oldh.Hash()
 	}
-	if oldh.Number.Uint64() < pool.clearIdx {
-		pool.clearIdx = oldh.Number.Uint64()
-	}
-	// roll back old blocks
-	for _, hash := range oldHashes {
-		pool.rollbackTxs(hash, txc)
+
+	if newHeader == nil {
```
Comment (tzdybal) [inline light/txpool.go]: This statement doesn't make much sense, especially in here.
Above, we assign `newHeader` to `newh`, and operate on `newh`. If `newHeader` was indeed `nil`, this would fail (except degenerated case when both `newh`/`newHeader` and `oldHeader` are `nil`).

If it actually can happen, or we want to be extra defensive, move the check above line 229.

**Review by tzdybal — CHANGES_REQUESTED** [review]
Is it possible to easily reproduce the issue in the test?

File: light/txpool.go (hunk 1 above)
Comment (meowsbits) [reply light/txpool.go]: I was assuming `oldh` was nil...

Comment (meowsbits) [reply light/txpool.go]: PTAL at changes thru https://github.com/etclabscore/core-geth/pull/54/commits/687e62601410c098332757dec8291df50daa4ffe.

Have added some test cases and simplified the checks.

**Review by tzdybal — APPROVED** [review]
