### PR TITLE
Fix discovery external docs URL

### LINKED ISSUE #297: rpc: discovery to return correct link for methods' externalDocs
Calling the `rpc_discover` gives wrong links to our repo codebase.

#### System information

```
CoreGeth
Version: 1.11.21-unstable
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: darwin
GOPATH=/Users/ziogaschr/Sites/go
GOROOT=/usr/local/Cellar/go/1.15.5/libexec
```

#### Expected behaviour
To point at our repo `etclabscore/core-geth`

```
"externalDocs": {
        "description": "Github remote link",
        "url": "https://github.com/etclabscore/core-geth/blob/master/internal/ethapi/api.go#L2004"
      }
```

#### Actual behaviour

It points at Ethereum repo `ethereum/go-ethereum`

```
"externalDocs": {
        "description": "Github remote link",
        "url": "https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L2004"
      }
```

### PR DESCRIPTION
**Pull request by ziogaschr**
The RPC discovery document was returning links to GitHub repo of `ethereum/go-ethereum`. This PR makes those links, link back to our `etclabscore/core-geth` repo.

On top of that, this PR also adds link to our [documentation site](https://etclabscore.github.io/core-geth/) for the whole discovery document. This link has to be updated to the final page made available by #306.

Fixes #297

### CODE REVIEW

File: node/openrpc.go [hunk 1]
```diff
@@ -56,7 +56,12 @@ var sharedMetaRegisterer = &go_openrpc_reflect.MetaT{
 		return info
 	},
 	GetExternalDocsFn: func() (exdocs *meta_schema.ExternalDocumentationObject) {
-		return nil // FIXME
+		exdocs = &meta_schema.ExternalDocumentationObject{}
+		description := "ETC Labs Documentation"
+		exdocs.Description = (*meta_schema.ExternalDocumentationObjectDescription)(&description)
+		url := "https://etclabscore.github.io/core-geth/"
```
Comment (ziogaschr) [inline node/openrpc.go:62]: @meowsbits can you please let me know of the URL which will be used for serving the discovery document in our docs website?

Comment (meowsbits) [reply node/openrpc.go:62]: Thanks for tagging this on; it'll be nice to have set.

How about let's leave the link as-is for now, and then #306 can be responsible for updating it when the precise URI gets firmed up.

Comment (ziogaschr) [reply node/openrpc.go:62]: Sounds perfect to me. Please review and merge this PR then

**Review by meowsbits — APPROVED** [review]
LGTM.

Example snippet provided as generated locally:

```
{
  "openrpc": "1.2.6", 
  "info": {
    "title": "Core-Geth RPC API", 
    "version": "1.11.22-unstable/generated-at:2021-01-20T15:07:56-06:00"
  }, 
  "externalDocs": {
    "description": "ETC Labs Documentation", 
    "url": "https://etclabscore.github.io/core-geth/"
  }, 
  "servers": [
    {
      "url": "ws://127.0.0.1:8546", 
      "name": "tcp"
    }
  ], 
  "methods": [
    {
      "name": "admin_addPeer", 
      "description": "```go\nfunc (api *privateAdminAPI) AddPeer(url string) (bool, error) {\n\tserver := api.node.Server()\n\tif server == nil {\n\t\treturn false, ErrNodeStopped\n\t}\n\tnode, err := enode.Parse(enode.ValidSchemes, url)\n\tif err != nil {\n\t\treturn false, fmt.Errorf(\"invalid enode: %v\", err)\n\t}\n\tserver.AddPeer(node)\n\treturn true, nil\n}// AddPeer requests connecting to a remote node, and also maintaining the new\n// connection at all times, even reconnecting if it is lost.\n\n```", 
      "summary": "AddPeer requests connecting to a remote node, and also maintaining the new\nconnection at all times, even reconnecting if it is lost.\n", 
      "paramStructure": "by-position", 
      "params": [
        {
          "name": "url", 
          "description": "string", 
          "summary": "", 
          "schema": {
            "type": ["string"]
          }, 
          "required": true, 
          "deprecated": false
        }
      ], 
      "result": {
        "name": "bool", 
        "description": "bool", 
        "summary": "", 
        "schema": {
          "type": ["boolean"]
        }, 
        "required": true, 
        "deprecated": false
      }, 
      "deprecated": false, 
      "externalDocs": {
        "description": "Github remote link", 
        "url": "https://github.com/etclabscore/core-geth/blob/master/node/api.go#L65"
      }
    }, 
```
