### PR TITLE
Fixes 234

### LINKED ISSUE #234: incorrect seedhash for the eth_GetWork reply (ECIP-1099)
ethash/sealer is generating incorrect seedhash for the eth_GetWork reply. 

In the current Mordor testnet it returns 0x0518e1373ff88ccabb28493cac10cb0731313135d880dae0d846be6016ab9acf instead, which is valid for the 89th epoch and not 88th like specified in the ECIP-1099

### PR DESCRIPTION
**Pull request by iquidus**
Fixes an issue in which, makeWork was producing an incorrect seedHash post ecip-1099 activation, on previously odd epochs (e.g 89).

fixes #234

### CODE REVIEW

**Review by ziogaschr — APPROVED** [review]

**Comment by meowsbits** [comment]
Rel #238

File: consensus/ethash/sealer.go [hunk 1]
```diff
@@ -344,8 +344,10 @@ func (s *remoteSealer) loop() {
 //   result[3], hex encoded block number
 func (s *remoteSealer) makeWork(block *types.Block) {
 	hash := s.ethash.SealHash(block.Header())
+	epochLength := calcEpochLength(block.NumberU64(), s.ethash.config.ECIP1099Block)
+	epoch := calcEpoch(block.NumberU64(), epochLength)
 	s.currentWork[0] = hash.Hex()
-	s.currentWork[1] = common.BytesToHash(SeedHash(block.NumberU64())).Hex()
+	s.currentWork[1] = common.BytesToHash(SeedHash(epoch*epochLength + 1)).Hex()
```
Comment (meowsbits) [inline consensus/ethash/sealer.go]: `SeedHash` is also used in the `debug` API. 

```go
// SeedHash retrieves the seed hash of a block.
func (api *PublicDebugAPI) SeedHash(ctx context.Context, number uint64) (string, error) {
	block, _ := api.b.BlockByNumber(ctx, rpc.BlockNumber(number))
	if block == nil {
		return "", fmt.Errorf("block #%d not found", number)
	}
	return fmt.Sprintf("0x%x", ethash.SeedHash(number)), nil
}
```

> `internal/ethapi/api.go`

Does the logic there need to change too?

File: internal/ethapi/api.go [hunk 2]
```diff
@@ -1856,12 +1856,13 @@ func (api *PublicDebugAPI) PrintBlock(ctx context.Context, number uint64) (strin
...
 
 // SeedHash retrieves the seed hash of a block.
-func (api *PublicDebugAPI) SeedHash(ctx context.Context, number uint64) (string, error) {
+func (api *PublicDebugAPI) SeedHash(ctx context.Context, number uint64, epochLength uint64) (string, error) {
 	block, _ := api.b.BlockByNumber(ctx, rpc.BlockNumber(number))
 	if block == nil {
 		return "", fmt.Errorf("block #%d not found", number)
 	}
-	return fmt.Sprintf("0x%x", ethash.SeedHash(number)), nil
+	epoch := number / epochLength
```
Comment (ziogaschr) [inline internal/ethapi/api.go]: This changes the API signature, which might brake stuff for people. I am not sure that we want that. Can we check if the `api` exposes the config in order to check if Ecip1099 is enabled?

Comment (ziogaschr) [reply internal/ethapi/api.go]: Maybe using this `api.b.ChainConfig().GetEthashECIP1099Transition()`?

File: consensus/ethash/ethash.go [hunk 3]
```diff
@@ -792,3 +792,13 @@ func (ethash *Ethash) APIs(chain consensus.ChainHeaderReader) []rpc.API {
 func SeedHash(epoch uint64, epochLength uint64) []byte {
 	return seedHash(epoch, epochLength)
 }
+
+// CalcEpochLength returns the epoch length for a given block number (ECIP-1099)
+func CalcEpochLength(block uint64, ecip1099FBlock *uint64) uint64 {
```
Comment (ziogaschr) [inline consensus/ethash/ethash.go:797]: Do you think `GetEpochLength` fits better in this context?

Comment (meowsbits) [reply consensus/ethash/ethash.go:797]: IMO, it probably does... but `Calc` echos the pre-existing function `calcEpochLength`. Renaming the functions would add diffs for trivial benefits; I'd suggest postponing nice-to-haves like this till later.

**Review by meowsbits — APPROVED** [review]

File: consensus/ethash/sealer.go (hunk 1 above)
Comment (meowsbits) [reply consensus/ethash/sealer.go]: Done in subsequent commits.
